build:
  nodes:
    tests:
      environment:
        php: 7.3
      tests:
        override:
          - command: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
            coverage:
              file: coverage.clover
              format: clover
    analysis:
      environment:
        php: 7.3
      tests:
        override:
          - php-scrutinizer-run

filter:
  excluded_paths: [tests/*, examples/*]

checks:
  php:
    code_rating: true
    duplication: true
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_identation_4spaces: true
    fix_doc_comments: true
    no_trailing_whitespace: true
    avoid_unnecessary_concatenation: true
    prefer_while_loop_over_for_loop: true
    parameter_doc_comments: true
    no_empty_statements: true
    no_debug_code: true
    no_commented_out_code: true
    newline_at_end_of_file: true
