build:
  image: default-bionic
  environment:
    php: '7.4' # Default PHP version

  nodes:
    php 7.3:
      environment:
        php: '7.3'
        COMPOSER_FLAGS: '--prefer-lowest'
    php 7.4:
      environment:
        php: '7.4'
    php 8.0:
      environment:
        php: '8.0'
    php 8.1:
      environment:
        php: '8.1'
    php 8.2:
      environment:
        php: '8.2'

    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
    excluded_paths: [tests/*]

checks:
    php:
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

tools:
    external_code_coverage:
        timeout: 600
        runs: 3
